import { Link } from "react-router-dom";

export default function Terms() {
  return (
    <div className="min-h-screen bg-black pt-32 pb-20 px-6">
      <div className="max-w-3xl mx-auto">
        <Link to="/" className="text-gold text-sm hover:text-gold-light transition-colors">&larr; Back to Home</Link>
        <h1 className="font-serif text-4xl text-white mt-6 mb-2">Terms of Use &amp; Disclaimer</h1>
        <p className="text-white/40 text-sm mb-12">Last Updated: April 13, 2026</p>

        <div className="space-y-8 text-white/70 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">1. No Attorney-Client Relationship</h2>
            <p>Use of this website, submission of a contact form, consultation request, or any other communication through this website does not create an attorney-client relationship between you and the Law Office of Justin D. Leigh or any of its attorneys. An attorney-client relationship is established only through a signed engagement letter or retainer agreement.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">2. Not Legal Advice</h2>
            <p>The information provided on this website is for general informational purposes only and does not constitute legal advice. The information may not reflect the most current legal developments and should not be relied upon as a substitute for legal counsel. Every legal situation is unique, and you should consult with a qualified attorney regarding your specific circumstances.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">3. Confidential Information</h2>
            <p>Please do not send any confidential or sensitive information through this website until a formal attorney-client relationship has been established through a signed engagement letter. Information submitted through contact forms, AI consultation requests, or other website features prior to engagement is not protected by attorney-client privilege. Once an attorney-client relationship is established, communications through our secure client portal are protected.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">4. No Guarantee of Results</h2>
            <p>Any case results, testimonials, or descriptions of past matters on this website are provided for illustrative purposes only. Prior results do not guarantee a similar outcome in your case. The outcome of any legal matter depends on a variety of factors unique to each case.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">5. Jurisdictions</h2>
            <p>Justin D. Leigh is licensed to practice law in the State of Washington (WSBA #55307) and the State of Oregon. This website may be considered attorney advertising in some jurisdictions. The hiring of a lawyer is an important decision that should not be based solely upon advertisements.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">6. Google Local Service Ads</h2>
            <p>If you found us through a Google Local Service Ad, please be aware of the following:</p>
            <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
              <li>Calls placed through Google Local Service Ads may be recorded by Google and are <span className="text-white/90 font-medium">not protected by attorney-client privilege</span></li>
              <li>Contact through a Google Local Service Ad does not establish an attorney-client relationship</li>
              <li>Google may modify ad content; our office does not control all aspects of the LSA listing</li>
              <li>For privileged communications, please contact our office directly after a formal engagement is established</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">7. Phone Calls and Recordings</h2>
            <p>Calls to our office may be recorded for quality assurance, training, and documentation purposes. By calling our office, you consent to the recording of the call. If you do not wish to be recorded, please inform us at the beginning of the call and we will accommodate your request.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">8. AI and Technology Services</h2>
            <p>Our website may feature AI-assisted consultation or inquiry tools. These tools are designed to gather initial information about your legal needs and do not provide legal advice. Responses generated by AI systems are not reviewed by an attorney in real-time and should not be relied upon as legal guidance. A qualified attorney will review your inquiry and respond personally.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">9. External Links</h2>
            <p>This website may contain links to third-party websites. We are not responsible for the content, privacy practices, or terms of use of any linked websites. Inclusion of a link does not constitute an endorsement.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">10. Intellectual Property</h2>
            <p>All content on this website, including text, graphics, logos, and design elements, is the property of the Law Office of Justin D. Leigh and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works from this content without prior written consent.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">11. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, the Law Office of Justin D. Leigh disclaims all liability for any damages arising from your use of this website or reliance on information contained herein. This website is provided "as is" without warranties of any kind.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">12. Governing Law</h2>
            <p>These Terms of Use are governed by the laws of the State of Washington. Any disputes arising from the use of this website shall be resolved in the courts of Washington State.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">13. Contact</h2>
            <div className="bg-white/5 border border-white/10 rounded-lg p-5">
              <p className="text-white font-medium">Justin D. Leigh, Attorney at Law</p>
              <p>Law Office of Justin D. Leigh</p>
              <p>Goldendale, Washington</p>
              <p className="mt-2">Phone: <a href="tel:5097738469" className="text-gold hover:text-gold-light transition-colors">(509) 773-8469</a></p>
              <p>Email: <a href="mailto:justindleigh@gmail.com" className="text-gold hover:text-gold-light transition-colors">justindleigh@gmail.com</a></p>
              <p className="mt-2">WSBA #55307</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
